syntax on
set nu
set hlsearch
set backspace=indent,eol,start

map <F3> :silent! Tlist<CR>

if has("autocmd")
	autocmd BufRead *.txt set tw=78
	autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g'\"" | endif
endif
